### PR TITLE
Fetch TTS

### PR DESCRIPTION
**Pull request by sivertheisholt**
Provides a way to fetch TTS that uses character voices to generate the speech and ability to play the audio in browser.
Puppeteer disables audio by default in headless mode, so added puppeteerIgnoreDefaultArgs.

### CODE REVIEW

**Comment by Parking-Master** [comment]
This looks very nice! @realcoloride shall have a look though. I also like the "puppeteerIgnoreDefaultArgs" that you added. Thanks for using my code too!

**Comment by realcoloride** [comment]
__I did not understand THIS type of audio fetching exactly but now its clear.__

 I thought you wanted to fetch the data to do something else FROM node_characterai and not playing the audio from puppeteer itself. But since fetchTTS does both, I prefer that fetchTTS remains for fetching.
Playing the audio via puppeteer should be separated. 

Some changes in the code I'd do:
`if(playAudio) AudioPlayer.playAudio(this.requester.page, speechBase64)` and `, playAudio = false)`
Remove these arguments. 

fetchTTS means to fetch and retrieve the information only and not playing the audio. If they would wish, they could use AudioPlayer.playAudio themselves or requester.playAudio()/client.playAudio() (see below). I'd also recommend to rename it into `.playAudioInBrowser()` to avoid confusion of what its playing and how its playing exactly. 

## And since audio control is probably also limited (by factors such as the speaker device), additional testing might be necessary.

Aswell for `this.requester.page`, it should not be required to refer the page, so its best to merge AudioPlayer inside of client.js or requester.js in order to directly access the client, which contains the requester (and the page). A dedicated class is perhaps not needed for one function only.

*Side note, I also don't know what playing an audio from a puppeteer instance (even a hidden one)'s performance cost is.*

*And in between client.js or requester.js, I personally prefer requester.js as its related to the browser/puppeteer, so requester makes more sense (atleast to me).*

```js
        try
        {
            await page.evaluate(`let TTS = new Audio("data:audio/wav;base64,${base64}"); TTS.play()`);
        } catch(error)
        {
            console.log("Could not play audio:", error)
        }
```
**This code violates convention.**

Correct convention & more efficient:
```js
        try {
            await page.evaluate(`new Audio("data:audio/wav;base64,${base64}").play()`); // no need to create a new variable here if its used only once
        } catch (error) {
            // console.log("Could not play audio:", error);
            // This should be replaced. It doesnt follow how ncai prints out errors. Instead do:
            throw Error("Content is invalid or not an image");
        }
```

### Another thing that worries me is the fact you use the `plus.` subdomain.
 I currently don't have CharacterAI+ and so many users and would not like them to be restricted by this feature. If its intended to be a CAI+ feature only (again, I didn't test myself to know), please indicate it before CharacterAI make silent decisions like blocking the endpoint to normal users.

*Hoping I didn't forget anything,*
❤️ It looks good and thank you for the contribution! 

Keep me updated.

**Comment by sivertheisholt** [comment]
Thank you for the detailed feedback! I totally agree and I will do the changes tomorrow (Hopefully).

I can imagine using the plus subdomain will require having CAI+. If it is a CAI+ feature I don't know, I will have to check that one out with a new account, as it forces me over to the plus domain with my current account.

Regarding performance cost when playing audio is something that perhaps @Parking-Master has experience with? I can't imagine it's any difference from a normal audio tag being played on a page.

**Comment by Parking-Master** [comment]
@sivertheisholt
> Regarding performance cost when playing audio is something that perhaps @Parking-Master has experience with? I can't imagine it's any difference from a normal audio tag being played on a page.

Yep, that's how browsers use audio tags. They process it and use the `Audio()` function instead. It shouldn't make any difference regarding performance.

**Comment by sivertheisholt** [comment]
I have done the changes that you suggested (I think) @realcoloride

I tested with a new account, and the `beta .` endpoint works fine without CAI+.

**Comment by Parking-Master** [comment]
@sivertheisholt oh, I thought this was only a CAI+ thing? I'll have to check it out then since I don't have CAI+

**Comment by sivertheisholt** [comment]
> @sivertheisholt oh, I thought this was only a CAI+ thing? I'll have to check it out then since I don't have CAI+

Me too! But apparently if you are using plus account, it will use `plus .` domain for all endpoints. Very interesting way they have handled it, not something I have seen before.

**Comment by realcoloride** [comment]
Try catch still doesn't follow convention, toSpeak should perhaps be replaced with a more understandable, because I do not know what toSpeak means.
`if (voiceId == undefined || typeof(voiceId) != "number" || toSpeak == undefined || typeof(toSpeak) != "string") throw Error("Invalid arguments.");`
can be simplfied with
`if (!voiceId || !toSpeak || typeof(voiceId) != "number" || typeof(toSpeak) != "string") throw Error("Invalid arguments.");`

Incorrect spacing:
```js
            const response = await Parser.parseJSON(request);
            return response.speech;
```
Correct spacing:
```js
            const response = await Parser.parseJSON(request);

            return response.speech;
```
(see other returns)

Other than that it looks OK to me. Did not try it though.

**Comment by sivertheisholt** [comment]
I can fix, but would like some help on these:

> Try catch still doesn't follow convention, toSpeak should perhaps be replaced with a more understandable argument 

Do you have any examples of how to return error arg to follow convention? I just found this in the code so I followed that one:

`
} catch (error) {throw Error("Failed to delete message." + error);}
`

Regarding tospeak, would you prefer for example textToSpeech ?

**Comment by realcoloride** [comment]
Here from the first message, quote:

```js
        try {
            await page.evaluate(`new Audio("data:audio/wav;base64,${base64}").play()`); // no need to create a new variable here if its used only once
        } catch (error) {
            // console.log("Could not play audio:", error);
            // This should be replaced. It doesnt follow how ncai prints out errors. Instead do:
            throw Error("Error detail, or specify the error argument");
        }
```

> Regarding tospeak, would you prefer for example textToSpeech ?
What does toSpeak even does exactly?

**Comment by Parking-Master** [comment]
@realcoloride don't you have write access to PRs? I think you can edit it to your needs manually

**Comment by sivertheisholt** [comment]
> Here from the first message, quote:
> 
> ```js
>         try {
>             await page.evaluate(`new Audio("data:audio/wav;base64,${base64}").play()`); // no need to create a new variable here if its used only once
>         } catch (error) {
>             // console.log("Could not play audio:", error);
>             // This should be replaced. It doesnt follow how ncai prints out errors. Instead do:
>             throw Error("Error detail, or specify the error argument");
>         }
> ```
> 

Oh I see, only one of them is convention, I think specifying the error argument only then is the best for this one.
> > Regarding tospeak, would you prefer for example textToSpeech ?
> 
> What does toSpeak even do exactly?

toSpeak is the query param for the endpoint that is the text you wanna convert to speech.

**Comment by realcoloride** [comment]
No, it is about how the try { } catch { } looks. The error is already good enough.

**Comment by sivertheisholt** [comment]
> No, it is about how the try { } catch { } looks. The error is already good enough.

Ofc! I have worked in .NET way too long haha, been a while since I touched Node.

**Comment by Parking-Master** [comment]
@realcoloride sure! I'll test it ASAP.

**Comment by realcoloride** [comment]
Hello again.
After testing, fetching worked but playing in the browser didn't.

I don't know what caused it exactly but it might be because of the speaker device used or something about autoplay audios.

**Comment by sivertheisholt** [comment]
> Hello again. After testing, fetching worked but playing in the browser didn't.
> 
> I don't know what caused it exactly but it might be because of the speaker device used or something about autoplay audios.

Indeed I can imagine that one will have problems across devices. I read especially chromium is very picky here. For me it runs fine on WSL2 Ubuntu 22 using google chrome.

It's not really a required to have, only nice to have feature I guess. An option would be to just remove that feature and just keep the fetching? Or perhaps @Parking-Master knows a bit more about this.

**Comment by Parking-Master** [comment]
@sivertheisholt after checking both of your comments, @realcoloride  reminded me about something: __Autoplay!__

You need to enable autoplay when launching puppeteer. Please wait, I'll look up the argument you need...

**Comment by Parking-Master** [comment]
@realcoloride @sivertheisholt try this:

```javascript
await page.setAutoplayPolicy("allow");
```

It should enable autoplay

**Comment by sivertheisholt** [comment]
> @realcoloride @sivertheisholt try this:
> 
> ```js
> await page.setAutoplayPolicy("allow");
> ```
> 
> And also add this argument on startup/launch (requester.js):
> 
> ```js
> "--autoplay-policy=no-user-gesture-required"
> ```
> 
> It should enable autoplay. Also in the same tab the script is playing audio in, could you take a screenshot of the output in the console?

Thank you! Mine works out of the box, so I will have to try to break mine to test that one. Another thing to consider is not to have autoplay enabled by default. Should perhaps be a toggle somehow?

Also will this play all the audio on the page when allowed?

**Comment by Parking-Master** [comment]
@sivertheisholt
> Should perhaps be a toggle somehow?

You can use:
```javascript
await page.setAutoplayPolicy("allow");
```

Before the function `fetchTTS` is run.

Then use this:
```javascript
await page.setAutoplayPolicy("disallow");
```

At the very end of the function.

> Also will this play all the audio on the page when allowed?

As I know of, the only audio that should be playing on the page is the character's voice. You should be good to go.

**Comment by realcoloride** [comment]
Hello again! I've thought of perhaps another problem that could be caused.

If the audio is played on the current page, and the current page gets swapped to another link, wouldn't that cause an issue and cut off the TTS audio? I haven't tested yet

**Comment by Parking-Master** [comment]
@realcoloride that would, but the pages shouldn't be changing after puppeteer setup is complete, right?

**Comment by realcoloride** [comment]
I don't think so since one page handles all requests

**Comment by Parking-Master** [comment]
How about opening in a new tab?

**Comment by realcoloride** [comment]
I think thats bloated to be honest, I think this is perhaps too much for too little.

If possible find a way to make the user itself find a way to play the audio in the browser and not node_chararacterai, but otherwise keep the play audio in browser (in exchange for the issue I mentioned above).

**Comment by Parking-Master** [comment]
@realcoloride ok, got it.

I honestly think now that just getting the raw base64 audio is a better idea 😂

I'll leave it up to you and @sivertheisholt though. Maybe the user could decode the base64 audio, save it to their system, and play it with nodejs? The possibilities ar endless, so again, I agree. You should just leave out the automatic audio playing.

**Comment by sivertheisholt** [comment]
I also believe audio part should be removed as it doesn't really fit node_character. It's easy for the user to handle this themself instead. I will remove it when I get home today/tomorrow, been traveling so been busy.

**Comment by Parking-Master** [comment]
@sivertheisholt enjoy the rest of your vacation!

**Comment by Parking-Master** [comment]
@realcoloride just reminding you that this PR is still open :D

**Pull request merged**
