### PR TITLE
Flush local storage

### PR DESCRIPTION
**Pull request by monckey100**
See:
https://github.com/realcoloride/node_characterai/issues/73

### CODE REVIEW

**Comment by realcoloride** [comment]
The console.log(s) are unecessary and usePlus should be used to avoid extra time on users who only use CAI+ or don't use CAI+.

**Comment by monckey100** [comment]
> The console.log(s) are unecessary and usePlus should be used to avoid extra time on users who only use CAI+ or don't use CAI+.

this seemingly fixed my loop problem too and I'm using CAI+.

**Comment by realcoloride** [comment]
Really? Thats weird

Try again without printing just to see and tell me

**Comment by monckey100** [comment]
> Really? Thats weird
> 
> Try again without printing just to see and tell me

I'm wrong, after further testing, the issue persists.

**Review by Parking-Master — CHANGES_REQUESTED** [review]
Looks great, but there is no need for the console.log. I have tested it and it works either way. Thank you @monckey100 for this PR

**Comment by realcoloride** [comment]
Hello I've commited commit https://github.com/realcoloride/node_characterai/commit/a74c27df938c52c40476e4d56cb90b8347192887 
Could you perhaps try and see if that works better?

I've adapted your code for convention usage.

**Comment by Parking-Master** [comment]
@realcoloride you also have to update the NPM package, it's not updating the package

**Comment by realcoloride** [comment]
I am aware and waiting for you to try out the changes before I push them to the npm package.

**Comment by Parking-Master** [comment]
@realcoloride oh, ok lol.

yeah I tested it just to see if it worked. Seems too, also did some digging as to why it takes so long to authenticate but couldn't find anything else.

I can confirm it works :)

**Comment by realcoloride** [comment]
Does it take a while to authenticate?
If so i'll consider optimizations. However, if not, I will push through the update.

**Comment by Parking-Master** [comment]
The update works, yes, but the long authentication wait has been happening for a while. Feel free to push the update. Thanks again for everything

**Comment by realcoloride** [comment]
Will release the patch and investigate performance issues right after.

Thank you for your patience.

**Comment by Parking-Master** [comment]
@realcoloride thank you! :)

**Comment by Parking-Master** [comment]
This PR could be closed, because the newer version now contains it alright.

**Pull request closed without merging**
