### PR TITLE
moved args so they can be manipulated

### PR DESCRIPTION
**Pull request by monckey100**
Args may need manipulation, especially in cases where you are looking to change the user agent, modify how many processes to use, set timeout duration etc.

### CODE REVIEW

**Comment by realcoloride** [comment]
Good idea.
I will definetely commit however, I dont think I will push a dedicated version for now.

**Comment by monckey100** [comment]
@realcoloride alright, just glad to help. I added a few more args out of my own necessity

**Comment by realcoloride** [comment]
I wouldn't add the timeout as its necessary in case of a bug like in the last issue regarding #62, _as a request should never take more than 5 seconds or higher..._ & the timeout arg is not self explainatory enough, it should be more like `protocolTimeOut` and probably add the `puppeteer` fix in front of it, like `puppeteerArgs` -> `puppeteerLaunchArguments`.

The only commit I feel like might be necessary is this one: https://github.com/realcoloride/node_characterai/pull/63/commits/c807a7d6c3c395f61934dc297df14de62cf6fcd4

**Comment by monckey100** [comment]
> I wouldn't add the timeout as its necessary in case of a bug like in the last issue regarding #62, _as a request should never take more than 5 seconds or higher..._ & the timeout arg is not self explainatory enough, it should be more like `protocolTimeOut` and probably add the `puppeteer` fix in front of it, like `puppeteerArgs` -> `puppeteerLaunchArguments`.
> 
> The only commit I feel like might be necessary is this one: [c807a7d](https://github.com/realcoloride/node_characterai/commit/c807a7d6c3c395f61934dc297df14de62cf6fcd4)

I actually did use the timeOut, I was trying to run this in a 1gb 0.25 cpu micro server from Google, it would just hang and then crash, I upgraded to a 2gb 0.5 small server, it's now able to fully execute and run. Weirdly uses a lot of computing power on token authentication.

**Comment by realcoloride** [comment]
No I think that it was just an issue with the old update.
See #62

**Comment by monckey100** [comment]
> No I think that it was just an issue with the old update. See #62

I never used the old update, I started using this library on July 9th

**Comment by realcoloride** [comment]
Commit https://github.com/realcoloride/node_characterai/commit/85d4a848678c058f79d4ffc50500b99d206ba35f
Hello, I've added your suggestions and parts and arguments that you requested. Thank you for your contribution!

**Pull request closed without merging**
