### PR TITLE
added waiting time when web character.ai is busy

### PR DESCRIPTION
**Pull request by DutaKey**
I found that when authenticating it doesn't do anything next because the lib logs in when the web is in "waiting rooms", this is very fatal because the code is stuck there, it doesn't continue and doesn't stop either, I added code which waits for authentication during that character.ai specified, I Hope this helps.

if this code is not perfect, it can be improved in the future, thank you.

### CODE REVIEW

**Comment by realcoloride** [comment]
Hello, 
While this seems like a good idea and I haven't checked everything out yet, can you please check if the cloudflare title check applies for all languages and use cases?

**Comment by DutaKey** [comment]
There should be no problem with the language, because the default language is English.

for cheerio is just a shortcut that I tried to do because when I tried to use puppeteer it immediately issued an error, while when I did it with cheerio it didn't issue an error.

**Comment by DutaKey** [comment]
image

**Comment by realcoloride** [comment]
> There should be no problem with the language, because the default language is English.
> 
> for cheerio is just a shortcut that I tried to do because when I tried to use puppeteer it immediately issued an error, while when I did it with cheerio it didn't issue an error.

Please try to use puppeteer instead to avoid adding overhead or bloat to the package from adding a new dependency.
However, thank you for the help.

This will be reviewed soon, please stay up to date with other PRs #38, pushes are being made, so you might want to stay up to date with the code changes.

**Comment by DutaKey** [comment]
I will update the code soon without using cheerio, but the character.ai web position is not busy now, I will return to work on it when the server is busy.

**Pull request closed without merging**
