### PR TITLE
Fix beta domain used when plus subscriber

### LINKED ISSUE #91: Requests return 301 when using plus - Requests fail when using with NW.js/Electron
Hello,

When using plus it will redirect all requests to plus domain, so the first requests always returns 301. This works fine on its own, but when using this package with NW.js or Electron the 301 doesn't work. The request will just hang. I tried using a non plus account, and it all works fine because the request is never redirected. 

Fix for this would be to use the correct domain when set `usePlus` to true.

Im guessing when using it directly thru nodejs it will handle itself fine, but when you have electron/nwjs on top something happens.

### PR DESCRIPTION
**Pull request by sivertheisholt**
This fixes #91 

A few ways todo this, this is one of them.

### CODE REVIEW

**Comment by realcoloride** [comment]
This is probably bad. Why?

Well lets say someone made a request containing "beta" in the link (encoded URI), then that would be automatically replaced by "plus".

**Comment by sivertheisholt** [comment]
> This is probably bad. Why?
> 
> Well lets say someone made a request containing "beta" in the link (encoded URI), then that would be automatically replaced by "plus".

Yepp, that is very true. I just thought u wanted to keep it like that from what u mentioned in the issue. 

Replacing it using the index should be a better solution as the start will most likely never change unless they switch out their domain to something else.

**Comment by sivertheisholt** [comment]
@realcoloride this is javascript in its finest. Look at this lol, apparently replace function only replaces the first occurrence .

image

So replace should work fine?

**Comment by realcoloride** [comment]
I'll check. Regex might be an option aswell just in case.

**Comment by sivertheisholt** [comment]
> I'll check. Regex might be an option aswell just in case.

Yes regex would also work, although less readability and it does involve the overhead of regex pattern parsing.

**Comment by sivertheisholt** [comment]
Hi, any update on this @realcoloride ?

Been using it for a couple of months now from my fork, but would like to switch to using the original instead if the issue is resolved. 

Also they seem to be moving away from their beta/plus domain design, their redesigned page is: 
https://character.ai/?redesign=true

Network calls are still goin to beta/plus/neo domains tho.

**Comment by realcoloride** [comment]
Hello,
The issue should be solved.

For the moving away to their beta/plus domain, I have noticed that aswell but currently as long as the old interface & endpoints works, i'll continue using it (for compatibility reasons). I've seen they use a websocket aswell, which could perhaps make it more efficient to use.

However, looking at the ne interface it does look like they're using the neo endpoints and plus endpoints.
As of authentication, things seem to be the same.

**Comment by sivertheisholt** [comment]
Awesome! Thanks for the update.

The new interface feels pretty responsive and improved. Hopefully they wont do any sudden changes to the endpoints. Hoping for an official API before that happens :)

I will do some testing with Electron and close the PR + issue if everything works fine.

**Pull request closed without merging**
