### PR TITLE
Current implemented fixes (#80)

### PR DESCRIPTION
**Pull request by Parking-Master**
Updated API to latest requirements, fixed all community reported bugs, and cleaned up some code in all of the files.

https://github.com/Parking-Master/node_characterai

### CODE REVIEW

**Comment by realcoloride** [comment]
Amazing! I'll test that tomorrow and I'll review changes.
Thank you again!

**Comment by realcoloride** [comment]
Hello, may I ask why you removed uploadImage() and replaced it with uploadImageFromLink(imageUrl)?

**Comment by Parking-Master** [comment]
@realcoloride hey again, I don't see that anywhere and never changed any of the image functions

**Comment by Parking-Master** [comment]
Look at the real docs (https://github.com/realcoloride/node_characterai/blob/main/README.md) it doesn't show `uploadImage` anywhere

**Comment by Parking-Master** [comment]
Oh, whoopsies, it's because it was from version 1.1.3. I'll replace it with the newer functions tomorrow, sorry about that

**Comment by realcoloride** [comment]
No problem. Keep me updated!

**Comment by Parking-Master** [comment]
Hey, I've replaced the image upload functions. Could you try it now? Thanks

**Comment by Parking-Master** [comment]
I've also added a feature for MIME auto-detection when uploading an image, or you can specify it manually

**Comment by realcoloride** [comment]
Is jimp still used in the commits?

**Comment by Parking-Master** [comment]
@realcoloride yep, it wouldn't work without it

**Comment by Parking-Master** [comment]
Oh wait, I deleted it by accident, let me add it back

**Comment by realcoloride** [comment]
Great!
I will review README.md changes but it looks kinda good already.

**Comment by Parking-Master** [comment]
@realcoloride thanks, I also updated the README to include newer functions that changed over time, feel free to edit it also

**Comment by Parking-Master** [comment]
I also would like to thank you so much for this amazing project. Because of it, I've been able to build my own physical robot named Chip which responds to certain commands I setup and even controls things around my home.

Without this project, I wouldn't be able to do that. Building Chip was really fun, so again, thanks! :)

**Comment by realcoloride** [comment]
Oh wow! That's awesome!! I am also thankful to contributors like you that helped throughout the project that helped in times where it was rough (like when puppeteer was needed).

Thank you again for the support, I really appreciate it!

**Comment by Parking-Master** [comment]
> EDIT: Say hi to Chip for me!

Will do, lol!

**Comment by Parking-Master** [comment]
Update: Tomorrow I plan to add the final features.

I will be improving plus user usability, so things for plus users will be faster, more reliable, and easier to access/use.

**Comment by realcoloride** [comment]
Looking forward! So far I've tested it and its brilliant. I think the waiting time was cut by half?

Good work again!

**Comment by Parking-Master** [comment]
Hello, I've searched through the code and found out that everything is already easier for plus users. I did however fix a syntax error, and add a more random user agent so cloudflare can't block the request. Please let me know how it goes when you run it!

**Comment by Parking-Master** [comment]
@realcoloride have you tested it? Once testing is done you can push the commits

**Comment by realcoloride** [comment]
Sorry for the late reply.

I haven't tried the new commits yet since but I will as soon as possible
and review them.

I will keep you updated.

**Comment by Parking-Master** [comment]
@realcoloride thank you! Take as much time as you need.

**Comment by realcoloride** [comment]
Ok, so I have tested and reviewed most of the package. I did not try the image features yet but  however I'd like to point out some changes I'd like to point out:
- You should keep the character tag in package.json
- I'd like to know what we should do of the user agent detais in getHeaders() [client.js]
- Also I'd like to keep the requires in ./path and not ./path.js 
- The message "Could not get a reply because it was aborted. This might be because the output was filtered (NSFW)." should be changed to "Could not get the full reply because it was aborted. This happens often when the output was filtered for violent or explicit content." for more clarification
- The message `[node_character] Puppeteer - Warning: Chromium path for puppeteer could not be located. If the script does not work properly, you may need to specify a path to the chromium binary file.` should be replaced with `[node_characterai] Puppeteer - Warning: the specified Chromium path for puppeteer could not be located. If the script does not work properly, you may need to specify a path to the Chromium binary file/executable.`
- Async statements should stay as `async()` for convention and not `async ()`
- `console.log("[node_characterai] Puppeteer - Currently in cloudflare's waiting room. Time left: " + waitingRoomTimeLeft);` should stay as `console.log(`[node_characterai] Puppeteer - Currently in cloudflare's waiting room. Time left: ${waitingRoomTimeLeft}`);` for convention
- Comments specified in requester.js of `// compatibity reasons` should stay for clarity
- Handle chromium tabs cleanup should stay as a feature as currently (on windows atleast) when the process is closed the chromium instances stay alive even if they dont have a purpose
- For the README.md:
- - // First... // Then... should be instead `// Authenticating as a guest (use .authenticateWithToken() to use an account)` or something around these lines
- - // use response.text to use it in a string. | should stay as is or be modified with `// use response.text to use it in a string as response returns a reply.` for perhaps more clarification
- - "using your Access Token." should stay as "using an `accessToken`" because to implicitly say that you can use multiple access tokens for example.
- - `* Login with your account or a token using `authenticateWithToken()` - *for extra features and messaging*` should be perhaps something like `* Login with an account via a token using `authenticateWithToken()` - *for full features and unlimited messaging*` for clarification
- - `// If no mime type is specified, the script will automatically detect it` should be said more simplified for those not knowing what a mime type is, example: `If no mime type (file extension) is specified...`
- - await chat.sendAndAwaitResponse(...) should stay in one line for convention 
- - **This is where in versions 1.1 and higher, puppeteer is used (which uses a fake chromium emulator) to make requests with the API.** -> this is incorrect because it is not emulating chromium and is a real one, so its best to stay along the original line or precise its a chromium browser underneith the hood
- - For the puppeteer argument list they should either stay one line to contain the argument and comment with it or have no space between the lines
- - I personally prefer the line "💡 I recommend that you **frequently** update this package for bug fixes and new additions." over the "It's recommended..."

## Anyways I hope I didn't miss a detail. Thank you again for the brilliant work that you've put in. I didn't have enough time to test the image features but I will when I can.

I will keep you updated!

**Comment by Parking-Master** [comment]
@realcoloride jeez, that's one long list! I'll try to get it all done tomorrow. Thank you for responding!

**Comment by Parking-Master** [comment]
[ ] You should keep the character tag in package.json
[ ] I'd like to know what we should do of the user agent detais in getHeaders() [client.js]
[ ] Also I'd like to keep the requires in ./path and not ./path.js
[ ] The message "Could not get a reply because it was aborted. This might be because the output was filtered (NSFW)." should be changed to "Could not get the full reply because it was aborted. This happens often when the output was filtered for violent or explicit content." for more clarification
[ ] The message [node_character] Puppeteer - Warning: Chromium path for puppeteer could not be located. If the script does not work properly, you may need to specify a path to the chromium binary file. should be replaced with [node_characterai] Puppeteer - Warning: the specified Chromium path for puppeteer could not be located. If the script does not work properly, you may need to specify a path to the Chromium binary file/executable.
[ ] Async statements should stay as async() for convention and not async ()
[ ] console.log("[node_characterai] Puppeteer - Currently in cloudflare's waiting room. Time left: " + waitingRoomTimeLeft); should stay as console.log([node_characterai] Puppeteer - Currently in cloudflare's waiting room. Time left: ${waitingRoomTimeLeft}); for convention
[ ] Comments specified in requester.js of // compatibity reasons should stay for clarity
[ ] Handle chromium tabs cleanup should stay as a feature as currently (on windows atleast) when the process is closed the chromium instances stay alive even if they dont have a purpose
[ ] Updated README.md

**Comment by Parking-Master** [comment]
Done! Let me know what you think or if it needs more modifying :D

**Comment by realcoloride** [comment]
That was pretty fast! I'll do some last checks in a bit and I will push the update.

I will keep you updated!

**Comment by Parking-Master** [comment]
@realcoloride thanks! If it helps I've also mentioned the current working forked repo to a user in #82. They verified it's faster and does fix all their problems!

**Comment by realcoloride** [comment]
Hello there!

Everything should be ok. I will test the package one more time to see and I'll push the update. I will keep you updated!

**Comment by Parking-Master** [comment]
@realcoloride thanks for letting me know!

**Comment by YuzuTheNeko** [comment]
even after installing the branch with the fixes, im still getting this error
image
image

**Comment by YuzuTheNeko** [comment]
managed to fix it by adding extra checks in your code, though i dont think its the good way to do it

**Comment by Parking-Master** [comment]
@YuzuTheNeko thanks for reporting that! I'll fix it ASAP.

**Comment by Parking-Master** [comment]
@YuzuTheNeko hello, `length` is at requester.js line 171.

It seems to be a problem with the waiting room. I'll keep you updated,

**Comment by Parking-Master** [comment]
The issue seems to be fixed, could you try again please?

**Comment by YuzuTheNeko** [comment]
Yes, ill try

**Comment by YuzuTheNeko** [comment]
Its fixed, thank you!

**Comment by YuzuTheNeko** [comment]
Ok well, not fully lol
image

**Comment by Parking-Master** [comment]
@YuzuTheNeko  thanks for the feedback! The new error is actually pretty common, so you're in luck. I'll try to fix it ASAP, and keep you up to date.

**Comment by Parking-Master** [comment]
Ok, thanks for your patience. I've released a fix. Please try it again and let me know how it goes.

**Comment by YuzuTheNeko** [comment]
i will try it tomorrow, i also had to fix 2 of these to make it work (before you made the changes) so i guess its all good now, ill still try it tomorrow and give you the final result though :)

**Comment by Parking-Master** [comment]
@YuzuTheNeko Ok, thanks :D

**Comment by realcoloride** [comment]
Hey parking master the change made  `if (url.endsWith("/streaming/")) return;` seems relatively dodgy to me, are you sure this will work? because CAI use the /streaming/ endpoint to speak with characters

**Comment by Parking-Master** [comment]
@realcoloride I've changed it because that did not work. The only thing I changed after my updates is the `setRequestInterception(...)` is run for every url, not just /streaming/.

**Comment by realcoloride** [comment]
Ok!

I will wait for the user to tell us how it goes and I'll push the update if everything goes well.

**Comment by YuzuTheNeko** [comment]
all good now, thank you for the fixes

**Comment by Parking-Master** [comment]
@YuzuTheNeko awesome!

**Comment by realcoloride** [comment]
Alright!

Thank you for the support! I will push the update and update you. Thank you again for your work!

**Comment by Parking-Master** [comment]
@realcoloride I honestly don't know, lol. You added it and I found it was an incorrect version, so I edited the version. Should I remove it?

**Comment by realcoloride** [comment]
Yeah, I never remember adding that.

**Comment by Parking-Master** [comment]
Ok, I'll remove it

**Comment by realcoloride** [comment]
Excellent!
Pushing this tonight.

If anything let me know, same for anyone reading this. If unrelated, please open a new issue.

**Comment by Parking-Master** [comment]
@realcoloride thank you so much! I really appreciate it.

**Comment by realcoloride** [comment]
Sorry for the lack of updates. I had a lot of things that went on since. I am pushing the update.

**Comment by realcoloride** [comment]
Update `1.2.0` has been pushed and commited.
Please tell me how it goes and again, sorry for the lack of news and update, I had unexpected events that happened at the wrong time.

**Comment by Parking-Master** [comment]
@realcoloride thanks for the info! I'm testing it now.

**Pull request merged**
